apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ha-nginx.fullname" . }}
  labels:
    {{- include "ha-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ha-nginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "ha-nginx.labels" . | nindent 8 }}
      annotations:
        # Config change will trigger a rollout
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101   # nginx in alpine runs as 101 by default
        fsGroup: 101
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /health
              port: {{ ternary "https" "http" .Values.tls.enabled | quote }}
              scheme: {{ ternary "HTTPS" "HTTP" .Values.tls.enabled | quote }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ ternary "https" "http" .Values.tls.enabled | quote }}
              scheme: {{ ternary "HTTPS" "HTTP" .Values.tls.enabled | quote }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /etc/nginx/tls
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "ha-nginx.fullname" . }}-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ required "tls.enabled=true requires .tls.secretName" .Values.tls.secretName }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - topologyKey: "kubernetes.io/hostname"
          maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "ha-nginx.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
      {{- if not .Values.affinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "ha-nginx.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      {{- else }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
